// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opecyhihtyusvhhivhcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZWN5aGlodHl1c3ZoaGl2aGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTUzMjQsImV4cCI6MjA2ODI5MTMyNH0.ENjDt3dzQwh5ejTBuQEj6EVMdLeNw86nN98_Cj3J750";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});